version: 2.1

jobs:
  test:
    docker:
      - image: circleci/python:3.7
      - image: circleci/mysql:5.7-ram
        environment:
          MYSQL_ROOT_PASSWORD: rootpwd
          MYSQL_DATABASE: vis_test
          MYSQL_USER: vis
          MYSQL_PASSWORD: vispwd
    working_directory: ~/ghostdb
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements/ci.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: Install Requirements
          command: |
            python -m venv ../venv
            . ../venv/bin/activate
            pip install -r requirements/ci.txt
      - save_cache:
          paths:
            - ../venv
          key: v1-dependencies-{{ checksum "requirements/ci.txt" }}
      - run:
          name: Waiting for MySQL to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z 127.0.0.1 3306 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for MySQL && exit 1
      - run:
          name: Python Version
          command: python -V
      - run:
          name: Tests
          when: always
          environment:
            PYTHONPATH: ..
            GHOSTDB_DB_DSN: mysql://vis:vispwd@127.0.0.1:3306/vis_test
          command: |
            . ../venv/bin/activate
            python -m pytest \
              --pylama \
              --ignore=./ghostdb/alembic \
              --junitxml=../tests_artifacts/junit.xml \
              --cov=. --cov-report=xml:../tests_artifacts/coverage.xml --cov-report=html:../tests_artifacts/coverage/ \
              ghostdb/
      - store_test_results:
          path: ../tests_artifacts/
          destination: tests_artifacts
      - store_artifacts:
          path: ../tests_artifacts/
          destination: tests_artifacts

  build-pkg:
    docker:
      - image: circleci/python:3.7
    working_directory: ~/ghostdb
    steps:
      - checkout
      - run:
          name: Python Version
          command: python -V
      - run:
          name: Configure PyPi
          command: |
            echo -e "[distutils]" >> ~/.pypirc
            echo -e "index-servers = vis" >> ~/.pypirc
            echo -e "[vis]" >> ~/.pypirc
            echo -e "repository = http://35.202.197.198:8080/" >> ~/.pypirc
            echo -e "username = ghostdb" >> ~/.pypirc
            echo -e "password = $GHOSTDB_PYPI_PASSWORD" >> ~/.pypirc
      - run:
          name: Make and Upload Package
          command: python setup.py egg_info -b dev`date "+%Y%m%d%H%M"` sdist upload -r vis


orbs:
  jira: circleci/jira@1.0.5

workflows:
  version: 2.1

  ghostdb:
    jobs:
      - test:
          post-steps:
            - jira/notify
      - build-pkg:
          filters:
            branches:
              only:
                - master
          requires:
            - test
