"""orders

Revision ID: 1245c66dfc76
Revises: 22f820b613b6
Create Date: 2020-01-20 11:17:34.045012

"""
from alembic import op
import sqlalchemy as sa

import ghostdb


# revision identifiers, used by Alembic.
revision = '1245c66dfc76'
down_revision = '22f820b613b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', ghostdb.db.sqltypes.UUID(), nullable=False),
    sa.Column('corporation_id', ghostdb.db.sqltypes.UUID(), nullable=False),
    sa.Column('client_id', ghostdb.db.sqltypes.UUID(), nullable=False),
    sa.Column('pet_id', ghostdb.db.sqltypes.UUID(), nullable=False),
    sa.Column('provider_id', ghostdb.db.sqltypes.UUID(), nullable=False),
    sa.Column('invoice_date', sa.DateTime(), nullable=True),
    sa.Column('is_posted', sa.Boolean(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('collections', 'deleted', 'due', 'open', 'paid', 'uncollectible', 'void', name='orderstatus'), nullable=True),
    sa.Column('pms_ids', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_orders_client_id_clients')),
    sa.ForeignKeyConstraint(['corporation_id'], ['corporations.id'], name=op.f('fk_orders_corporation_id_corporations')),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], name=op.f('fk_orders_pet_id_pets')),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], name=op.f('fk_orders_provider_id_providers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orders'))
    )
    op.create_table('order_items',
    sa.Column('id', ghostdb.db.sqltypes.UUID(), nullable=False),
    sa.Column('order_id', ghostdb.db.sqltypes.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('revenue_center_id', ghostdb.db.sqltypes.UUID(), nullable=True),
    sa.Column('department_id', ghostdb.db.sqltypes.UUID(), nullable=True),
    sa.Column('category_id', ghostdb.db.sqltypes.UUID(), nullable=True),
    sa.Column('class_id', ghostdb.db.sqltypes.UUID(), nullable=True),
    sa.Column('subclass_id', ghostdb.db.sqltypes.UUID(), nullable=True),
    sa.Column('servicetype_id', ghostdb.db.sqltypes.UUID(), nullable=True),
    sa.Column('service_id', ghostdb.db.sqltypes.UUID(), nullable=True),
    sa.Column('quantity', sa.Numeric(), nullable=True),
    sa.Column('unit_price', sa.Numeric(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['glcode_category.id'], name=op.f('fk_order_items_category_id_glcode_category')),
    sa.ForeignKeyConstraint(['class_id'], ['glcode_class.id'], name=op.f('fk_order_items_class_id_glcode_class')),
    sa.ForeignKeyConstraint(['department_id'], ['glcode_department.id'], name=op.f('fk_order_items_department_id_glcode_department')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_order_items_order_id_orders')),
    sa.ForeignKeyConstraint(['revenue_center_id'], ['glcode_revenuecenter.id'], name=op.f('fk_order_items_revenue_center_id_glcode_revenuecenter')),
    sa.ForeignKeyConstraint(['service_id'], ['glcode_service.id'], name=op.f('fk_order_items_service_id_glcode_service')),
    sa.ForeignKeyConstraint(['servicetype_id'], ['glcode_servicetype.id'], name=op.f('fk_order_items_servicetype_id_glcode_servicetype')),
    sa.ForeignKeyConstraint(['subclass_id'], ['glcode_subclass.id'], name=op.f('fk_order_items_subclass_id_glcode_subclass')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_items'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_items')
    op.drop_table('orders')
    # ### end Alembic commands ###
