"""GL codes

Revision ID: 22f820b613b6
Revises: 49682ecffcd7
Create Date: 2020-01-15 14:54:57.182398

"""
from alembic import op
import sqlalchemy as sa

import ghostdb


# revision identifiers, used by Alembic.
revision = '22f820b613b6'
down_revision = '49682ecffcd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('glcode_category',
    sa.Column('id', ghostdb.db.sqltypes.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_vis_default', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_glcode_category')),
    sa.UniqueConstraint('name', name=op.f('uq_glcode_category_name'))
    )
    op.create_table('glcode_class',
    sa.Column('id', ghostdb.db.sqltypes.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_vis_default', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_glcode_class')),
    sa.UniqueConstraint('name', name=op.f('uq_glcode_class_name'))
    )
    op.create_table('glcode_department',
    sa.Column('id', ghostdb.db.sqltypes.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_vis_default', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_glcode_department')),
    sa.UniqueConstraint('name', name=op.f('uq_glcode_department_name'))
    )
    op.create_table('glcode_revenuecenter',
    sa.Column('id', ghostdb.db.sqltypes.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_vis_default', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_glcode_revenuecenter')),
    sa.UniqueConstraint('name', name=op.f('uq_glcode_revenuecenter_name'))
    )
    op.create_table('glcode_servicetype',
    sa.Column('id', ghostdb.db.sqltypes.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_vis_default', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_glcode_servicetype')),
    sa.UniqueConstraint('name', name=op.f('uq_glcode_servicetype_name'))
    )
    op.create_table('glcode_subclass',
    sa.Column('id', ghostdb.db.sqltypes.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_vis_default', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_glcode_subclass')),
    sa.UniqueConstraint('name', name=op.f('uq_glcode_subclass_name'))
    )
    op.create_table('glcode_service',
    sa.Column('id', ghostdb.db.sqltypes.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('kind', sa.Enum('service', 'product', 'inventory', 'admin', name='servicekind'), nullable=False),
    sa.Column('revenue_center_id', ghostdb.db.sqltypes.UUID(), nullable=True),
    sa.Column('department_id', ghostdb.db.sqltypes.UUID(), nullable=True),
    sa.Column('category_id', ghostdb.db.sqltypes.UUID(), nullable=True),
    sa.Column('class_id', ghostdb.db.sqltypes.UUID(), nullable=True),
    sa.Column('subclass_id', ghostdb.db.sqltypes.UUID(), nullable=True),
    sa.Column('servicetype_id', ghostdb.db.sqltypes.UUID(), nullable=True),
    sa.Column('is_vis_default', sa.Boolean(), nullable=True),
    sa.Column('pms_ids', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['glcode_category.id'], name=op.f('fk_glcode_service_category_id_glcode_category')),
    sa.ForeignKeyConstraint(['class_id'], ['glcode_class.id'], name=op.f('fk_glcode_service_class_id_glcode_class')),
    sa.ForeignKeyConstraint(['department_id'], ['glcode_department.id'], name=op.f('fk_glcode_service_department_id_glcode_department')),
    sa.ForeignKeyConstraint(['revenue_center_id'], ['glcode_revenuecenter.id'], name=op.f('fk_glcode_service_revenue_center_id_glcode_revenuecenter')),
    sa.ForeignKeyConstraint(['servicetype_id'], ['glcode_servicetype.id'], name=op.f('fk_glcode_service_servicetype_id_glcode_servicetype')),
    sa.ForeignKeyConstraint(['subclass_id'], ['glcode_subclass.id'], name=op.f('fk_glcode_service_subclass_id_glcode_subclass')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_glcode_service')),
    sa.UniqueConstraint('name', name=op.f('uq_glcode_service_name'))
    )
    # ### end Alembic commands ###

    data_upgrade()


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('glcode_service')
    op.drop_table('glcode_subclass')
    op.drop_table('glcode_servicetype')
    op.drop_table('glcode_revenuecenter')
    op.drop_table('glcode_department')
    op.drop_table('glcode_class')
    op.drop_table('glcode_category')
    # ### end Alembic commands ###


def data_upgrade():
    from ghostdb.db.models.code import RevenueCenter, Department, Category, Class, SubClass, ServiceType


    data = {
        RevenueCenter: (
            'GP', 'Specialty', 'Pet Resort', 'ER', 'Pet Supplyey', 'Other Medical', 'Hybrid',
        ),
        Department: (
            'Emergency', 'Cardiology', 'Opthalmology', 'Neurology', 'Training Services',
            'Grooming Services', 'Behavior', 'Oncology ', 'GP ', 'Dermatology',
            'Boarding Services', 'Reproductive ', 'Dentistry', 'Surgery', 'Radiology',
            'Exotics ', 'Internal Medicine', 'Critical Care', 'Day Care Services', 'Anesthesiology',
        ),
        Category: (
            'Consultation', 'Hospitalization', 'Diagnostic', 'Treatment', 'Surgery',
            'Procedure', 'Pharmacy',
        ),
        Class: (
            'Cardiology', 'Gastrointestinal', 'Opthalmology', 'Ectoparasite', 'Urogenital',
            'Respiratory', 'Steroids', 'Antibiotics', 'Antihelminthics', 'Laparoscopy',
            'Vitamins', 'Dentistry', 'Musculoskeletal', 'Critical Care', 'Emergency',
            'NSAIDS', 'Chemotherapeutics', 'Hospital Lab', 'Hospital', 'Immunotherapy',
            'Splint', 'Radiology', 'Internal Medicine', 'Antihistamines', 'Antivirals',
            'Liver', 'Boarding', 'Ectoparasites', 'Vaccine', 'Oncology',
            'Dermatology', 'Antacids', 'Food', 'Nutrition', 'Toxicology', 'Orthopedic',
            'Preventive Care', 'Surgical', 'Analgesia', 'Bandage', 'Antiemetics', 'Cast',
            'Antifungals', 'Death', 'Reproduction', 'Fluids', 'Reference Lab', 'Steriods',
            'Endocrine', 'Catheters', 'Neurology', 'Behavior', 'Infectious Disease',
            'Needle', 'Physical Therapy', 'Anesthesia', 'Hematology', 'Endoscopy',
            'Soft Tissue Surgery', 'Blood',
        ),
        SubClass: (
            'Placement', 'Gastrointestinal', 'Shampoo', 'Procedures', 'Respiratory', 'Urogenital',
            'OTC', 'Epidural', 'Oral', 'Transfusion', 'Vitamins', 'Donor', 'IV', 'Enteral',
            'Cover', 'Imaging', 'Drains', 'Laproscopic', 'Prescription', 'Therapy', 'CPCR',
            'Biopsy', 'Arthrodesis', 'Supply', 'Injectable', 'Limb Sparing', 'Otic', 'Tendon',
            'Euthanasia', 'Thorascopic', 'CNS', 'Joint', 'Spinal ', 'Additives', 'Laboratory',
            'Supplements', 'Miscellaneous', 'Pulmonary', 'Thoracic', 'Procedure', 'Spinal',
            'Abdominal', 'Respiratory - Upper', 'Luxation', 'Reproductive', 'Necropsy',
            'Hospitalization', 'Application', 'Transdermal', 'Disposal', 'Hepatosplenic',
            'Diagnostics', 'Monitoring', 'Surgery', 'Endodontics', 'Cremation', 'Amputation',
            'Oral Products', 'Products', 'Administration', 'Skin', 'Patient Care', 'Urinary',
            'Implants', 'Opthalmic', 'Inhalent', 'Bone Marrow', 'Wound', 'Consultation',
            'Medical Boarding', 'Closure', 'Endocrine', 'Cardiovascular', 'Fracture',
            'Diagnostic', 'Vascular', 'Periodontics', 'Nursing', 'Interventional', 'Collection',
            'Intravenous', 'Body Cavity', 'Burial',
        ),
        ServiceType: (
            'Trichogram', 'Fundic Exam', 'Immnohistochemistry', 'Episioplasty', 'CT',
            'Chemotherapy Admin', 'Mastectomy', 'Central', 'Skin Scrape',
            'Intradermal Allergy Test', 'Microbiology', 'Plates', 'Hypertonic',
            'Other', 'Intraosseous', 'Transtracheal Wash', 'Lens', 'Radiation Therapy',
            'CRI', 'Vaccines', 'Echocardiography', 'Blood Gas', 'IM Nails', 'OHE',
            'Vaginal Prolapse', 'Colloids', 'C-Section', 'Skin Biopsy', 'J-tube',
            'Impression Smear', 'Extraction', 'Foreign Body Extraction', 'Penile Amputation',
            'ECG', 'Abdomen', 'E-tube', 'Immunology', 'Bronchoscopy', 'Fecal', 'Lid',
            'Allergy Shots', 'Biopsy', 'ERG', 'Jejunostomy', 'Radiography', 'Ultrasound',
            'Contrast', 'Peripheral', 'Pyometra', 'Urine', 'Histopathology',
            'Prostatic Abscess', 'Urinary', 'Endocrine', 'Pins', 'Needle Aspirate', 'STT',
            'Endotracheal Wash', 'Screws', 'Supply', 'Upper GI', 'Chemistry', 'CO2',
            'TIVA', 'Profiles', 'Rhinoscopy', 'Prostatectomy', 'NIBP', 'Local ',
            'Tracheoscopy', 'MRI', 'PCR', 'Sevoflurane', 'Otoscopy', 'SpO2', 'General ',
            'Castration', 'Flouroscein', 'Corneal', 'Serology', 'Vaccination', 'G-tube',
            'Tensilon Test', 'IBP', 'Hematology', 'Radiosurgery', 'Globe', 'Retinal',
            'Cytology', 'External Fixation', 'Isoflurane', 'Epidural', 'Sedation',
            'Gingival Sx', 'Set-up & Administration', 'Gait Analysis', 'Myelography',
            'Immunotherapy', 'Esophagostomy', 'Lower GI', 'Cystalloids', 'Chest',
            'Bone Marrow Aspirate', 'Tonometry', 'Gastric', 'Uterine Prolapse',
            'Bone Marrow Biopsy',
        ),
    }

    for klass, names in data.items():
        op.bulk_insert(
            klass.__table__,
            [{'name': name, 'is_vis_default': True} for name in names]
        )
