"""consolidator models

Revision ID: 24603686c811
Revises:
Create Date: 2020-01-03 12:30:39.670677

"""
from alembic import op
import sqlalchemy as sa

import ghostdb


# revision identifiers, used by Alembic.
revision = '24603686c811'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consolidators',
    sa.Column('id', ghostdb.db.sqltypes.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_consolidators'))
    )
    op.create_table('consolidator_integrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consolidator_id', ghostdb.db.sqltypes.UUID(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('module', sa.Enum('vetsuccess', name='integrationmodules'), nullable=True),
    sa.Column('auth_credentials', sa.JSON(), nullable=True),
    sa.Column('is_enable', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['consolidator_id'], ['consolidators.id'], name=op.f('fk_consolidator_integrations_consolidator_id_consolidators')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_consolidator_integrations'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('consolidator_integrations')
    op.drop_table('consolidators')
    # ### end Alembic commands ###
