"""appointment model

Revision ID: 3ff3a87c4cc1
Revises: 9b9b9cd60a57
Create Date: 2020-01-09 16:02:08.116092

"""
from alembic import op
import sqlalchemy as sa

import ghostdb


# revision identifiers, used by Alembic.
revision = '3ff3a87c4cc1'
down_revision = '9b9b9cd60a57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointments',
    sa.Column('id', ghostdb.db.sqltypes.UUID(), nullable=False),
    sa.Column('practice_id', ghostdb.db.sqltypes.UUID(), nullable=True),
    sa.Column('provider_id', ghostdb.db.sqltypes.UUID(), nullable=True),
    sa.Column('patient_id', ghostdb.db.sqltypes.UUID(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('scheduled_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('ADMITTED', 'CANCELLED', 'CHECKED_IN', 'CHECKING_OUT', 'COMPLETED', 'CONFIRMED', 'DAYCARE', 'INPROGRESS', 'MEDBOARD', 'NOSHOW', 'PENDING', 'PLANNED', 'LATE', 'RESERVATION', 'KEPT', 'RESCHEDULED', name='status'), nullable=True),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_appointments_patient_id_patients')),
    sa.ForeignKeyConstraint(['practice_id'], ['practices.id'], name=op.f('fk_appointments_practice_id_practices')),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], name=op.f('fk_appointments_provider_id_providers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_appointments'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('appointments')
    # ### end Alembic commands ###
