"""extend order models with vetsuccess data

Revision ID: 4932465e5494
Revises: 29063a6a709c
Create Date: 2020-02-25 12:41:40.090723

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql


# revision identifiers, used by Alembic.
revision = '4932465e5494'
down_revision = '29063a6a709c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'orders',
        'status',
        existing_type=mysql.ENUM('COLLECTIONS', 'DELETED', 'DUE', 'OPEN', 'PAID', 'UNCOLLECTIBLE', 'VOID', 'CLOSED'),
        nullable=True
    )
    op.add_column('order_items', sa.Column('amount', sa.Numeric(), nullable=True))
    op.add_column('order_items', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('order_items', sa.Column('discount_amount', sa.Numeric(), nullable=True))
    op.add_column('order_items', sa.Column('free_doses', sa.Numeric(), nullable=True))
    op.add_column('order_items', sa.Column('is_depletion_only', sa.Boolean(), nullable=True))
    op.add_column('order_items', sa.Column('is_hidden_on_invoice', sa.Boolean(), nullable=True))
    op.add_column('order_items', sa.Column('is_posted', sa.Boolean(), nullable=True))
    op.add_column('order_items', sa.Column('is_voided', sa.Boolean(), nullable=True))
    op.add_column('order_items', sa.Column('paid_doses', sa.Numeric(), nullable=True))
    op.add_column('order_items', sa.Column('pms_ids', sa.JSON(), nullable=True))
    op.drop_constraint('fk_order_items_servicetype_id_glcode_servicetype', 'order_items', type_='foreignkey')
    op.drop_constraint('fk_order_items_category_id_glcode_category', 'order_items', type_='foreignkey')
    op.drop_constraint('fk_order_items_class_id_glcode_class', 'order_items', type_='foreignkey')
    op.drop_constraint('fk_order_items_subclass_id_glcode_subclass', 'order_items', type_='foreignkey')
    op.drop_constraint('fk_order_items_department_id_glcode_department', 'order_items', type_='foreignkey')
    op.drop_constraint('fk_order_items_revenue_center_id_glcode_revenuecenter', 'order_items', type_='foreignkey')
    op.drop_column('order_items', 'subclass_id')
    op.drop_column('order_items', 'category_id')
    op.drop_column('order_items', 'servicetype_id')
    op.drop_column('order_items', 'class_id')
    op.drop_column('order_items', 'revenue_center_id')
    op.drop_column('order_items', 'department_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'orders',
        'status',
        existing_type=mysql.ENUM('collections', 'deleted', 'due', 'open', 'paid', 'uncollectible', 'void'),
        nullable=True
    )
    op.add_column('order_items', sa.Column('department_id', sa.BINARY(length=16), nullable=True))
    op.add_column('order_items', sa.Column('revenue_center_id', sa.BINARY(length=16), nullable=True))
    op.add_column('order_items', sa.Column('class_id', sa.BINARY(length=16), nullable=True))
    op.add_column('order_items', sa.Column('servicetype_id', sa.BINARY(length=16), nullable=True))
    op.add_column('order_items', sa.Column('category_id', sa.BINARY(length=16), nullable=True))
    op.add_column('order_items', sa.Column('subclass_id', sa.BINARY(length=16), nullable=True))
    op.create_foreign_key('fk_order_items_revenue_center_id_glcode_revenuecenter', 'order_items', 'glcode_revenuecenter', ['revenue_center_id'], ['id'])
    op.create_foreign_key('fk_order_items_department_id_glcode_department', 'order_items', 'glcode_department', ['department_id'], ['id'])
    op.create_foreign_key('fk_order_items_subclass_id_glcode_subclass', 'order_items', 'glcode_subclass', ['subclass_id'], ['id'])
    op.create_foreign_key('fk_order_items_class_id_glcode_class', 'order_items', 'glcode_class', ['class_id'], ['id'])
    op.create_foreign_key('fk_order_items_category_id_glcode_category', 'order_items', 'glcode_category', ['category_id'], ['id'])
    op.create_foreign_key('fk_order_items_servicetype_id_glcode_servicetype', 'order_items', 'glcode_servicetype', ['servicetype_id'], ['id'])
    op.drop_column('order_items', 'pms_ids')
    op.drop_column('order_items', 'paid_doses')
    op.drop_column('order_items', 'is_voided')
    op.drop_column('order_items', 'is_posted')
    op.drop_column('order_items', 'is_hidden_on_invoice')
    op.drop_column('order_items', 'is_depletion_only')
    op.drop_column('order_items', 'free_doses')
    op.drop_column('order_items', 'discount_amount')
    op.drop_column('order_items', 'description')
    op.drop_column('order_items', 'amount')
    # ### end Alembic commands ###
