"""extend gl code service model with fields from VetSuccess

Revision ID: 4f2c90d83a4e
Revises: a7dba094d8c1
Create Date: 2020-02-19 17:45:23.136671

"""
from alembic import op
import sqlalchemy as sa

import ghostdb


# revision identifiers, used by Alembic.
revision = '4f2c90d83a4e'
down_revision = 'a7dba094d8c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('glcode_service', sa.Column('active', sa.Boolean(), nullable=True))
    op.add_column('glcode_service', sa.Column('base_price', sa.Numeric(), nullable=True))
    op.add_column('glcode_service', sa.Column('business_id', ghostdb.db.sqltypes.UUID(), nullable=True))
    op.add_column('glcode_service', sa.Column('category_description', sa.String(length=200), nullable=True))
    op.add_column('glcode_service', sa.Column('dispensing_fee', sa.Numeric(), nullable=True))
    op.add_column('glcode_service', sa.Column('free_doses', sa.Numeric(), nullable=True))
    op.add_column('glcode_service', sa.Column('paid_doses', sa.Numeric(), nullable=True))
    op.add_column('glcode_service', sa.Column('unit_of_measure', sa.String(length=50), nullable=True))
    op.add_column('glcode_service', sa.Column('verified', sa.Boolean(), nullable=True))
    op.create_foreign_key(op.f('fk_glcode_service_business_id_businesses'), 'glcode_service', 'businesses', ['business_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_glcode_service_business_id_businesses'), 'glcode_service', type_='foreignkey')
    op.drop_column('glcode_service', 'verified')
    op.drop_column('glcode_service', 'unit_of_measure')
    op.drop_column('glcode_service', 'paid_doses')
    op.drop_column('glcode_service', 'free_doses')
    op.drop_column('glcode_service', 'dispensing_fee')
    op.drop_column('glcode_service', 'category_description')
    op.drop_column('glcode_service', 'business_id')
    op.drop_column('glcode_service', 'base_price')
    op.drop_column('glcode_service', 'active')
    # ### end Alembic commands ###
