"""add site_id to Order

Revision ID: 727aa3837572
Revises: 9a786e2d9a9b
Create Date: 2020-03-17 15:45:30.993826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '727aa3837572'
down_revision = '9a786e2d9a9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('site_id', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'site_id')
    # ### end Alembic commands ###
