"""add source and kind relations to appointment model

Revision ID: 7306945eaa3d
Revises: d41bdf16de37
Create Date: 2020-02-14 11:17:58.464221

"""
from alembic import op
import sqlalchemy as sa

import ghostdb


# revision identifiers, used by Alembic.
revision = '7306945eaa3d'
down_revision = 'd41bdf16de37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointment_kinds',
    sa.Column('id', ghostdb.db.sqltypes.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_appointment_kinds')),
    sa.UniqueConstraint('name', name=op.f('uq_appointment_kinds_name'))
    )
    op.create_table('appointment_sources',
    sa.Column('id', ghostdb.db.sqltypes.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_appointment_sources')),
    sa.UniqueConstraint('name', name=op.f('uq_appointment_sources_name'))
    )
    op.add_column('appointments', sa.Column('kind_id', ghostdb.db.sqltypes.UUID(), nullable=True))
    op.add_column('appointments', sa.Column('source_id', ghostdb.db.sqltypes.UUID(), nullable=True))
    op.create_foreign_key(op.f('fk_appointments_source_id_appointment_sources'), 'appointments', 'appointment_sources', ['source_id'], ['id'])
    op.create_foreign_key(op.f('fk_appointments_kind_id_appointment_kinds'), 'appointments', 'appointment_kinds', ['kind_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_appointments_kind_id_appointment_kinds'), 'appointments', type_='foreignkey')
    op.drop_constraint(op.f('fk_appointments_source_id_appointment_sources'), 'appointments', type_='foreignkey')
    op.drop_column('appointments', 'source_id')
    op.drop_column('appointments', 'kind_id')
    op.drop_table('appointment_sources')
    op.drop_table('appointment_kinds')
    # ### end Alembic commands ###
