"""practice models

Revision ID: 9908431eb832
Revises: 24603686c811
Create Date: 2020-01-08 11:30:08.333215

"""
from alembic import op
import sqlalchemy as sa

import ghostdb


# revision identifiers, used by Alembic.
revision = '9908431eb832'
down_revision = '24603686c811'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('practices',
    sa.Column('id', ghostdb.db.sqltypes.UUID(), nullable=False),
    sa.Column('consolidator_id', ghostdb.db.sqltypes.UUID(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('open_date', sa.Date(), nullable=True),
    sa.Column('longitude', sa.Numeric(), nullable=True),
    sa.Column('latitude', sa.Numeric(), nullable=True),
    sa.Column('zip_code', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('pms_ids', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['consolidator_id'], ['consolidators.id'], name=op.f('fk_practices_consolidator_id_consolidators')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_practices'))
    )
    op.create_table('practice_contacts',
    sa.Column('id', ghostdb.db.sqltypes.UUID(), nullable=False),
    sa.Column('practice_id', ghostdb.db.sqltypes.UUID(), nullable=True),
    sa.Column('kind', sa.Enum('phone', 'email', 'website', name='contactkind'), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('value', sa.String(length=100), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['practice_id'], ['practices.id'], name=op.f('fk_practice_contacts_practice_id_practices')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_practice_contacts'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('practice_contacts')
    op.drop_table('practices')
    # ### end Alembic commands ###
