"""provider models

Revision ID: 9b9b9cd60a57
Revises: 9908431eb832
Create Date: 2020-01-08 18:03:18.018888

"""
from alembic import op
import sqlalchemy as sa

import ghostdb


# revision identifiers, used by Alembic.
revision = '9b9b9cd60a57'
down_revision = '9908431eb832'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider_kinds',
    sa.Column('id', ghostdb.db.sqltypes.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('is_doctor', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_provider_kinds')),
    sa.UniqueConstraint('name', name=op.f('uq_provider_kinds_name'))
    )
    op.create_table('providers',
    sa.Column('id', ghostdb.db.sqltypes.UUID(), nullable=False),
    sa.Column('practice_id', ghostdb.db.sqltypes.UUID(), nullable=True),
    sa.Column('kind_id', ghostdb.db.sqltypes.UUID(), nullable=True),
    sa.Column('first_name', sa.String(length=200), nullable=True),
    sa.Column('last_name', sa.String(length=200), nullable=True),
    sa.Column('is_user', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('pms_ids', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['kind_id'], ['provider_kinds.id'], name=op.f('fk_providers_kind_id_provider_kinds')),
    sa.ForeignKeyConstraint(['practice_id'], ['practices.id'], name=op.f('fk_providers_practice_id_practices')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_providers'))
    )
    op.create_table('provider_contacts',
    sa.Column('id', ghostdb.db.sqltypes.UUID(), nullable=False),
    sa.Column('provider_id', ghostdb.db.sqltypes.UUID(), nullable=True),
    sa.Column('kind', sa.Enum('phone', 'email', 'website', name='contactkind'), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('value', sa.String(length=100), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], name=op.f('fk_provider_contacts_provider_id_providers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_provider_contacts'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('provider_contacts')
    op.drop_table('providers')
    op.drop_table('provider_kinds')
    # ### end Alembic commands ###
