"""pms_id field for business contact

Revision ID: d41bdf16de37
Revises: a0e125afbce6
Create Date: 2020-02-12 12:41:55.457069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd41bdf16de37'
down_revision = 'a0e125afbce6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business_contacts', sa.Column('pms_ids', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('business_contacts', 'pms_ids')
    # ### end Alembic commands ###
