"""client models

Revision ID: e1f103c99b27
Revises: 24603686c811
Create Date: 2020-01-03 16:12:01.092542

"""
from alembic import op
import sqlalchemy as sa

import ghostdb


# revision identifiers, used by Alembic.
revision = 'e1f103c99b27'
down_revision = '24603686c811'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', ghostdb.db.sqltypes.UUID(), nullable=False),
    sa.Column('bussiness_name', sa.String(length=200), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('pms_ids', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clients'))
    )
    op.create_table('client_addresses',
    sa.Column('id', ghostdb.db.sqltypes.UUID(), nullable=False),
    sa.Column('client_id', ghostdb.db.sqltypes.UUID(), nullable=True),
    sa.Column('kind', sa.Enum('home', 'work', 'temporary', name='addresskind'), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('zip_code', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_client_addresses_client_id_clients')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_client_addresses'))
    )
    op.create_table('client_contacts',
    sa.Column('id', ghostdb.db.sqltypes.UUID(), nullable=False),
    sa.Column('client_id', ghostdb.db.sqltypes.UUID(), nullable=True),
    sa.Column('kind', sa.Enum('mobile', 'home', 'work', name='contactkind'), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('value', sa.String(length=50), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_client_contacts_client_id_clients')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_client_contacts'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('client_contacts')
    op.drop_table('client_addresses')
    op.drop_table('clients')
    # ### end Alembic commands ###
