"""add user deleted

Revision ID: 008aeed38f44
Revises: 12bf3a5853dc
Create Date: 2020-11-11 14:51:56.177063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '008aeed38f44'
down_revision = '12bf3a5853dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('deleted', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'deleted')
    # ### end Alembic commands ###
