"""corporation name not uniq and not required

Revision ID: 0a59360ccd58
Revises: 197e35583d60
Create Date: 2020-10-20 16:09:09.260526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a59360ccd58'
down_revision = '197e35583d60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('corporations', 'name',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.drop_constraint('uq_corporations_name', 'corporations', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_corporations_name', 'corporations', ['name'])
    op.alter_column('corporations', 'name',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    # ### end Alembic commands ###
