"""Extend member model with fields for Org Chart

Revision ID: 12bf3a5853dc
Revises: acec3b322d2e
Create Date: 2020-11-03 14:42:23.039457

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '12bf3a5853dc'
down_revision = 'acec3b322d2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('is_temporary', sa.Boolean(), nullable=True))
    op.add_column('members', sa.Column('position', sa.String(length=100), nullable=True))
    op.add_column('members', sa.Column('responsibilities', sa.Text(), nullable=True))
    op.add_column('members', sa.Column('role', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('members', 'role')
    op.drop_column('members', 'responsibilities')
    op.drop_column('members', 'position')
    op.drop_column('members', 'is_temporary')
    # ### end Alembic commands ###
