"""maturity level for corporation

Revision ID: 197e35583d60
Revises: 9c5bceb4dbed
Create Date: 2020-10-20 11:06:30.751413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '197e35583d60'
down_revision = '9c5bceb4dbed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('corporations', sa.Column('maturity_level', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('corporations', 'maturity_level')
    # ### end Alembic commands ###
