"""cascade delete temp tokens on user deleting

Revision ID: 1a38b29d9a5f
Revises: 6f21aa205eaa
Create Date: 2020-12-21 13:28:01.122686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a38b29d9a5f'
down_revision = '6f21aa205eaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_temporary_token_user_id_users', 'temporary_token', type_='foreignkey')
    op.create_foreign_key(op.f('fk_temporary_token_user_id_users'), 'temporary_token', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_temporary_token_user_id_users'), 'temporary_token', type_='foreignkey')
    op.create_foreign_key('fk_temporary_token_user_id_users', 'temporary_token', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
