"""kpi_value add created_at and updated_at

Revision ID: 1e8a07b60f88
Revises: 2196f958c578
Create Date: 2020-09-01 13:32:20.831823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e8a07b60f88'
down_revision = '2196f958c578'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kpi_value', sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=True))
    op.add_column('kpi_value', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kpi_value', 'updated_at')
    op.drop_column('kpi_value', 'created_at')
    # ### end Alembic commands ###
