"""add utc

Revision ID: 2196f958c578
Revises: 8d87a332a1b8
Create Date: 2020-08-28 17:10:40.526283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2196f958c578'
down_revision = '8d87a332a1b8'
branch_labels = None
depends_on = None

tables = [
        'appointments',
        'appointment_sources',
        'appointment_kinds',
        'businesses',
        'clients',
        'glcode_revenuecenter',
        'glcode_department',
        'glcode_category',
        'glcode_class',
        'glcode_subclass',
        'glcode_servicetype',
        'glcode_service',
        'corporations',
        'corporation_integrations',
        'orders',
        'order_items',
        'breeds',
        'colors',
        'genders',
        'species',
        'weightunits',
        'pets',
        'providers'
    ]


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    for table in tables:
        op.alter_column(
            table,
            'created_at',
            type_=sa.DateTime(),
            server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
            existing_nullable=True
        )
        op.alter_column(
            table,
            'updated_at',
            type_=sa.DateTime(),
            server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
            existing_nullable=True
        )
        op.execute(f"UPDATE {table} SET created_at = created_at AT TIME ZONE 'UTC'")
        op.execute(f"UPDATE {table} SET updated_at = updated_at AT TIME ZONE 'UTC'")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    for table in tables:
        op.alter_column(
            table,
            'created_at',
            type_=sa.DateTime(),
            server_default=sa.text('now()'),
            existing_nullable=True
        )
        op.alter_column(
            table,
            'updated_at',
            type_=sa.DateTime(),
            server_default=None,
            existing_nullable=True
        )
    # ### end Alembic commands ###
