"""add missed pms_ids field to appointment model

Revision ID: 272323879d92
Revises: 7306945eaa3d
Create Date: 2020-02-14 14:15:01.702547

"""
from alembic import op
import sqlalchemy as sa

import ghostdb


# revision identifiers, used by Alembic.
revision = '272323879d92'
down_revision = '7306945eaa3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('pms_ids', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointments', 'pms_ids')
    # ### end Alembic commands ###
