"""back to FK relations in Serice to GL Codes

Revision ID: 3cb7539c31cb
Revises: de76967e8612
Create Date: 2020-09-03 13:53:05.336360

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3cb7539c31cb'
down_revision = 'de76967e8612'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('glcode_srv_servicetype_rel')
    op.drop_table('glcode_srv_subclass_rel')
    op.add_column('glcode_service', sa.Column('servicetype_id', ghostdb.db.sqltypes.UUID(), nullable=True))
    op.add_column('glcode_service', sa.Column('subclass_id', ghostdb.db.sqltypes.UUID(), nullable=True))
    op.create_foreign_key(op.f('fk_glcode_service_subclass_id_glcode_subclass'), 'glcode_service', 'glcode_subclass', ['subclass_id'], ['id'])
    op.create_foreign_key(op.f('fk_glcode_service_servicetype_id_glcode_servicetype'), 'glcode_service', 'glcode_servicetype', ['servicetype_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_glcode_service_servicetype_id_glcode_servicetype'), 'glcode_service', type_='foreignkey')
    op.drop_constraint(op.f('fk_glcode_service_subclass_id_glcode_subclass'), 'glcode_service', type_='foreignkey')
    op.drop_column('glcode_service', 'subclass_id')
    op.drop_column('glcode_service', 'servicetype_id')
    op.create_table('glcode_srv_subclass_rel',
    sa.Column('subclass', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('service', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['service'], ['glcode_service.id'], name='fk_glcode_srv_subclass_rel_service_glcode_service'),
    sa.ForeignKeyConstraint(['subclass'], ['glcode_subclass.id'], name='fk_glcode_srv_subclass_rel_subclass_glcode_subclass')
    )
    op.create_table('glcode_srv_servicetype_rel',
    sa.Column('service_type', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('service', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['service'], ['glcode_service.id'], name='fk_glcode_srv_servicetype_rel_service_glcode_service'),
    sa.ForeignKeyConstraint(['service_type'], ['glcode_servicetype.id'], name='fk_glcode_srv_servicetype_rel_service_type_glcode_servicetype')
    )
    # ### end Alembic commands ###
