"""KPI values table

Revision ID: 3f03170b8c57
Revises: 61c99c1854b7
Create Date: 2020-05-20 12:55:32.314226

"""
from alembic import op
import sqlalchemy as sa

import ghostdb


# revision identifiers, used by Alembic.
revision = '3f03170b8c57'
down_revision = '61c99c1854b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kpi_value',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('FINANCIAL_NET_REVENUE', 'FINANCIAL_NET_PROFIT', name='kpikind'), nullable=True),
    sa.Column('value', sa.Numeric(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('corporation_id', ghostdb.db.sqltypes.UUID(), nullable=True),
    sa.Column('business_id', ghostdb.db.sqltypes.UUID(), nullable=True),
    sa.Column('provider_id', ghostdb.db.sqltypes.UUID(), nullable=True),
    sa.Column('client_id', ghostdb.db.sqltypes.UUID(), nullable=True),
    sa.Column('pet_id', ghostdb.db.sqltypes.UUID(), nullable=True),
    sa.Column('revenue_center_id', ghostdb.db.sqltypes.UUID(), nullable=True),
    sa.Column('department_id', ghostdb.db.sqltypes.UUID(), nullable=True),
    sa.Column('category_id', ghostdb.db.sqltypes.UUID(), nullable=True),
    sa.Column('class_id', ghostdb.db.sqltypes.UUID(), nullable=True),
    sa.Column('subclass_id', ghostdb.db.sqltypes.UUID(), nullable=True),
    sa.Column('servicetype_id', ghostdb.db.sqltypes.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], name=op.f('fk_kpi_value_business_id_businesses')),
    sa.ForeignKeyConstraint(['category_id'], ['glcode_category.id'], name=op.f('fk_kpi_value_category_id_glcode_category')),
    sa.ForeignKeyConstraint(['class_id'], ['glcode_class.id'], name=op.f('fk_kpi_value_class_id_glcode_class')),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_kpi_value_client_id_clients')),
    sa.ForeignKeyConstraint(['corporation_id'], ['corporations.id'], name=op.f('fk_kpi_value_corporation_id_corporations')),
    sa.ForeignKeyConstraint(['department_id'], ['glcode_department.id'], name=op.f('fk_kpi_value_department_id_glcode_department')),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], name=op.f('fk_kpi_value_pet_id_pets')),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], name=op.f('fk_kpi_value_provider_id_providers')),
    sa.ForeignKeyConstraint(['revenue_center_id'], ['glcode_revenuecenter.id'], name=op.f('fk_kpi_value_revenue_center_id_glcode_revenuecenter')),
    sa.ForeignKeyConstraint(['servicetype_id'], ['glcode_servicetype.id'], name=op.f('fk_kpi_value_servicetype_id_glcode_servicetype')),
    sa.ForeignKeyConstraint(['subclass_id'], ['glcode_subclass.id'], name=op.f('fk_kpi_value_subclass_id_glcode_subclass')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_kpi_value'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kpi_value')
    # ### end Alembic commands ###
