"""corporation members

Revision ID: 417ed42b77a6
Revises: a854e15c373a
Create Date: 2020-10-13 17:43:15.147126

"""
from alembic import op
import sqlalchemy as sa

import ghostdb


# revision identifiers, used by Alembic.
revision = '417ed42b77a6'
down_revision = 'a854e15c373a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('members',
    sa.Column('id', ghostdb.db.sqltypes.UUID(), nullable=False),
    sa.Column('user_id', ghostdb.db.sqltypes.UUID(), nullable=True),
    sa.Column('corporation_id', ghostdb.db.sqltypes.UUID(), nullable=True),
    sa.Column('invite_id', sa.String(length=96), nullable=True),
    sa.Column('date_of_join', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['corporation_id'], ['corporations.id'], name=op.f('fk_members_corporation_id_corporations')),
    sa.ForeignKeyConstraint(['invite_id'], ['temporary_token.token'], name=op.f('fk_members_invite_id_temporary_token')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_members_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_members'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('members')
    # ### end Alembic commands ###
