"""add new options to client_family.relation

Revision ID: 491713e4423d
Revises: 8d87a332a1b8
Create Date: 2020-08-27 16:48:19.305957

"""
from alembic import op
import sqlalchemy as sa
import ghostdb
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '491713e4423d'
down_revision = '8d87a332a1b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    opts = ['sibling', 'spouse', 'partner', 'other']
    for opt in opts:
        op.execute(f"ALTER TYPE familyrelation ADD VALUE '{opt}';")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
