"""client family relation

Revision ID: 49682ecffcd7
Revises: 15d334d540b4
Create Date: 2020-01-13 17:05:50.425764

"""
from alembic import op
import sqlalchemy as sa

import ghostdb


# revision identifiers, used by Alembic.
revision = '49682ecffcd7'
down_revision = '15d334d540b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_family',
    sa.Column('id', ghostdb.db.sqltypes.UUID(), nullable=False),
    sa.Column('from_client_id', ghostdb.db.sqltypes.UUID(), nullable=False),
    sa.Column('to_client_id', ghostdb.db.sqltypes.UUID(), nullable=False),
    sa.Column('relation', sa.Enum('parent', 'child', name='familyrelation'), nullable=True),
    sa.ForeignKeyConstraint(['from_client_id'], ['clients.id'], name=op.f('fk_client_family_from_client_id_clients')),
    sa.ForeignKeyConstraint(['to_client_id'], ['clients.id'], name=op.f('fk_client_family_to_client_id_clients')),
    sa.PrimaryKeyConstraint('id', 'from_client_id', 'to_client_id', name=op.f('pk_client_family'))
    )
    op.add_column('corporation_integrations', sa.Column('corporation_id', ghostdb.db.sqltypes.UUID(), nullable=False))
    op.drop_constraint('fk_corporation_integrations_consolidator_id_corporations', 'corporation_integrations', type_='foreignkey')
    op.create_foreign_key(op.f('fk_corporation_integrations_corporation_id_corporations'), 'corporation_integrations', 'corporations', ['corporation_id'], ['id'])
    op.drop_column('corporation_integrations', 'consolidator_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('corporation_integrations', sa.Column('consolidator_id', sa.BINARY(length=16), nullable=False))
    op.drop_constraint(op.f('fk_corporation_integrations_corporation_id_corporations'), 'corporation_integrations', type_='foreignkey')
    op.create_foreign_key('fk_corporation_integrations_consolidator_id_corporations', 'corporation_integrations', 'corporations', ['consolidator_id'], ['id'])
    op.drop_column('corporation_integrations', 'corporation_id')
    op.drop_table('client_family')
    # ### end Alembic commands ###
