"""order status options

Revision ID: 4b2703323dfb
Revises: 3f03170b8c57
Create Date: 2020-05-28 14:53:11.652261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b2703323dfb'
down_revision = '3f03170b8c57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'orders',
        'status',
        existing_type=sa.Enum(
            'COLLECTIONS', 'DELETED', 'DUE', 'OPEN', 'PAID', 'UNCOLLECTIBLE', 'VOID', 'CLOSED', 'UNFINISHED',
            name='orderstatus'
        ),
        nullable=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'orders',
        'status',
        existing_type=sa.Enum(
            'COLLECTIONS', 'DELETED', 'DUE', 'OPEN', 'PAID', 'UNCOLLECTIBLE', 'VOID',
            name='orderstatus'
        ),
        nullable=True
    )
    # ### end Alembic commands ###
