"""created user model

Revision ID: 4edb2e9eb97a
Revises: 401676a61a1a
Create Date: 2020-09-21 17:51:20.367829

"""
from alembic import op
import sqlalchemy as sa

import ghostdb

# revision identifiers, used by Alembic.
revision = '4edb2e9eb97a'
down_revision = '401676a61a1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', ghostdb.db.sqltypes.UUID(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('first_name', sa.String(length=200), nullable=True),
    sa.Column('last_name', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('salt', sa.String(length=32), nullable=True),
    sa.Column('last_changed_password', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_visited', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_table('members',
    sa.Column('user_id', ghostdb.db.sqltypes.UUID(), nullable=False),
    sa.Column('corporation_id', ghostdb.db.sqltypes.UUID(), nullable=False),
    sa.Column('date_of_join', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['corporation_id'], ['corporations.id'], name=op.f('fk_members_corporation_id_corporations')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_members_user_id_users')),
    sa.PrimaryKeyConstraint('user_id', 'corporation_id', name=op.f('pk_members'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('members')
    op.drop_table('users')
    # ### end Alembic commands ###
