"""timezone for business model

Revision ID: 4f64f6a8b9f3
Revises: 27b5caf49eef
Create Date: 2020-08-26 16:40:33.988375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f64f6a8b9f3'
down_revision = '27b5caf49eef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('timezone', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('businesses', 'timezone')
    # ### end Alembic commands ###
