"""user-corporation fk relation

Revision ID: 626ad1272dac
Revises: 8d392c241774
Create Date: 2020-09-29 12:56:37.951160

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

import ghostdb

# revision identifiers, used by Alembic.
revision = '626ad1272dac'
down_revision = '8d392c241774'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('members')
    op.add_column('users', sa.Column('corporation_id', ghostdb.db.sqltypes.UUID(), nullable=True))
    op.add_column('users', sa.Column('date_of_join', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('is_ghost', sa.Boolean(), nullable=True))
    op.create_unique_constraint(op.f('uq_users_email'), 'users', ['email'])
    op.create_foreign_key(op.f('fk_users_corporation_id_corporations'), 'users', 'corporations', ['corporation_id'], ['id'])
    op.drop_column('users', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('fk_users_corporation_id_corporations'), 'users', type_='foreignkey')
    op.drop_constraint(op.f('uq_users_email'), 'users', type_='unique')
    op.drop_column('users', 'is_ghost')
    op.drop_column('users', 'date_of_join')
    op.drop_column('users', 'corporation_id')
    op.create_table('members',
    sa.Column('user_id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('corporation_id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('date_of_join', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['corporation_id'], ['corporations.id'], name='fk_members_corporation_id_corporations'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_members_user_id_users'),
    sa.PrimaryKeyConstraint('user_id', 'corporation_id', name='pk_members')
    )
    # ### end Alembic commands ###
