"""remove corporation integration model

Revision ID: 73cbf5f8ef0c
Revises: 82e4edfe0ac9
Create Date: 2021-02-01 11:01:48.556284

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '73cbf5f8ef0c'
down_revision = '82e4edfe0ac9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('corporation_integrations')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('corporation_integrations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('corporation_id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('module', postgresql.ENUM('vetsuccess', name='integrationmodules'), autoincrement=False, nullable=False),
    sa.Column('auth_credentials', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('is_enable', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text("timezone('utc'::text, CURRENT_TIMESTAMP)"), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text("timezone('utc'::text, CURRENT_TIMESTAMP)"), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['corporation_id'], ['corporations.id'], name='fk_corporation_integrations_corporation_id_corporations'),
    sa.PrimaryKeyConstraint('id', name='pk_corporation_integrations')
    )
    # ### end Alembic commands ###
