"""Temporary Token storage

Revision ID: 8d392c241774
Revises: 4edb2e9eb97a
Create Date: 2020-09-23 17:53:37.992124

"""
from alembic import op
import sqlalchemy as sa

import ghostdb


# revision identifiers, used by Alembic.
revision = '8d392c241774'
down_revision = '4edb2e9eb97a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('temporary_token',
    sa.Column('token', sa.String(length=96), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', ghostdb.db.sqltypes.UUID(), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_temporary_token_user_id_users')),
    sa.PrimaryKeyConstraint('token', name=op.f('pk_temporary_token'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('temporary_token')
    # ### end Alembic commands ###
