"""pet and provider not required fields for order

Revision ID: 9a786e2d9a9b
Revises: 4932465e5494
Create Date: 2020-02-26 11:46:45.099054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a786e2d9a9b'
down_revision = '4932465e5494'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'pet_id',
               existing_type=sa.BINARY(length=16),
               nullable=True)
    op.alter_column('orders', 'provider_id',
               existing_type=sa.BINARY(length=16),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'provider_id',
               existing_type=sa.BINARY(length=16),
               nullable=False)
    op.alter_column('orders', 'pet_id',
               existing_type=sa.BINARY(length=16),
               nullable=False)
    # ### end Alembic commands ###
