"""kind for temporary token

Revision ID: 9c5bceb4dbed
Revises: 417ed42b77a6
Create Date: 2020-10-16 15:18:51.706895

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '9c5bceb4dbed'
down_revision = '417ed42b77a6'
branch_labels = None
depends_on = None


def upgrade():
    token_kind = postgresql.ENUM('EMAIL_VALIDATION', 'CORPORATION_INVITE', name='tokenkind')
    token_kind.create(op.get_bind())

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'temporary_token',
        sa.Column(
            'kind',
            token_kind,
            nullable=True
        )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('temporary_token', 'kind')
    # ### end Alembic commands ###

    token_kind = postgresql.ENUM('EMAIL_VALIDATION', 'CORPORATION_INVITE', name='tokenkind')
    token_kind.drop(op.get_bind())
