"""pms_id field for client address and contact

Revision ID: a0e125afbce6
Revises: 1ec2ad3ee1e9
Create Date: 2020-02-04 11:25:37.349697

"""
from alembic import op
import sqlalchemy as sa

import ghostdb


# revision identifiers, used by Alembic.
revision = 'a0e125afbce6'
down_revision = '1ec2ad3ee1e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_addresses', sa.Column('pms_ids', sa.JSON(), nullable=True))
    op.add_column('client_contacts', sa.Column('pms_ids', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client_contacts', 'pms_ids')
    op.drop_column('client_addresses', 'pms_ids')
    # ### end Alembic commands ###
