"""ordering for members

Revision ID: a65b0fdec7ae
Revises: 33bf6a077978
Create Date: 2021-01-11 13:31:44.605709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a65b0fdec7ae'
down_revision = '33bf6a077978'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('ordering', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('members', 'ordering')
    # ### end Alembic commands ###
