"""GL Code service kind extend list, sublass and service type changed to M2M

Revision ID: a7dba094d8c1
Revises: 8c71bb174500
Create Date: 2020-02-19 15:23:14.710837

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

import ghostdb

# revision identifiers, used by Alembic.
revision = 'a7dba094d8c1'
down_revision = '8c71bb174500'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('glcode_srv_servicetype_rel',
    sa.Column('service_type', ghostdb.db.sqltypes.UUID(), nullable=True),
    sa.Column('service', ghostdb.db.sqltypes.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['service'], ['glcode_service.id'], name=op.f('fk_glcode_srv_servicetype_rel_service_glcode_service')),
    sa.ForeignKeyConstraint(['service_type'], ['glcode_servicetype.id'], name=op.f('fk_glcode_srv_servicetype_rel_service_type_glcode_servicetype'))
    )
    op.create_table('glcode_srv_subclass_rel',
    sa.Column('subclass', ghostdb.db.sqltypes.UUID(), nullable=True),
    sa.Column('service', ghostdb.db.sqltypes.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['service'], ['glcode_service.id'], name=op.f('fk_glcode_srv_subclass_rel_service_glcode_service')),
    sa.ForeignKeyConstraint(['subclass'], ['glcode_subclass.id'], name=op.f('fk_glcode_srv_subclass_rel_subclass_glcode_subclass'))
    )
    op.add_column('glcode_category', sa.Column('pms_ids', sa.JSON(), nullable=True))
    op.add_column('glcode_class', sa.Column('pms_ids', sa.JSON(), nullable=True))
    op.add_column('glcode_department', sa.Column('pms_ids', sa.JSON(), nullable=True))
    op.add_column('glcode_revenuecenter', sa.Column('pms_ids', sa.JSON(), nullable=True))
    op.alter_column('glcode_service', 'kind',
               existing_type=mysql.ENUM('SERVICE', 'PRODUCT', 'INVENTORY', 'ADMIN', 'GROUPITEM', 'DISCOUNT', 'MEDICAL', 'DIAGNOSTIC', 'SALES_TAX', 'PROBLEM', 'PAYMENT', 'TYPE'),
               nullable=True)
    op.drop_index('uq_glcode_service_name', table_name='glcode_service')
    op.drop_constraint('fk_glcode_service_servicetype_id_glcode_servicetype', 'glcode_service', type_='foreignkey')
    op.drop_constraint('fk_glcode_service_subclass_id_glcode_subclass', 'glcode_service', type_='foreignkey')
    op.drop_column('glcode_service', 'subclass_id')
    op.drop_column('glcode_service', 'servicetype_id')
    op.add_column('glcode_servicetype', sa.Column('pms_ids', sa.JSON(), nullable=True))
    op.add_column('glcode_subclass', sa.Column('pms_ids', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('glcode_subclass', 'pms_ids')
    op.drop_column('glcode_servicetype', 'pms_ids')
    op.add_column('glcode_service', sa.Column('servicetype_id', sa.BINARY(length=16), nullable=True))
    op.add_column('glcode_service', sa.Column('subclass_id', sa.BINARY(length=16), nullable=True))
    op.create_foreign_key('fk_glcode_service_subclass_id_glcode_subclass', 'glcode_service', 'glcode_subclass', ['subclass_id'], ['id'])
    op.create_foreign_key('fk_glcode_service_servicetype_id_glcode_servicetype', 'glcode_service', 'glcode_servicetype', ['servicetype_id'], ['id'])
    op.create_index('uq_glcode_service_name', 'glcode_service', ['name'], unique=True)
    op.alter_column('glcode_service', 'kind',
               existing_type=mysql.ENUM('service', 'product', 'inventory', 'admin'),
               nullable=False)
    op.drop_column('glcode_revenuecenter', 'pms_ids')
    op.drop_column('glcode_department', 'pms_ids')
    op.drop_column('glcode_class', 'pms_ids')
    op.drop_column('glcode_category', 'pms_ids')
    op.drop_table('glcode_srv_subclass_rel')
    op.drop_table('glcode_srv_servicetype_rel')
    # ### end Alembic commands ###
