"""member with tree structure

Revision ID: acec3b322d2e
Revises: 0a59360ccd58
Create Date: 2020-11-02 14:41:54.020777

"""
from alembic import op
import sqlalchemy as sa

import sqlalchemy_utils.types.ltree


# revision identifiers, used by Alembic.
revision = 'acec3b322d2e'
down_revision = '0a59360ccd58'
branch_labels = None
depends_on = None


def upgrade():
    op.execute('CREATE EXTENSION IF NOT EXISTS ltree')
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=True))
    op.add_column('members', sa.Column('path', sqlalchemy_utils.types.ltree.LtreeType(), nullable=True))
    op.add_column('members', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('members', 'updated_at')
    op.drop_column('members', 'path')
    op.drop_column('members', 'created_at')
    # ### end Alembic commands ###
