"""is_inventory transaction flag for order item

Revision ID: ad97a1d9655a
Revises: 4b2703323dfb
Create Date: 2020-06-01 17:16:55.221167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad97a1d9655a'
down_revision = '4b2703323dfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('is_inventory', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_items', 'is_inventory')
    # ### end Alembic commands ###
