"""add new status to appointment

Revision ID: ae16495f8747
Revises: 272323879d92
Create Date: 2020-02-17 10:57:13.897259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae16495f8747'
down_revision = '272323879d92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'appointments',
        'status',
        existing_type=sa.Enum(
            'ADMITTED', 'CANCELLED', 'CHECKED_IN', 'CHECKING_OUT', 'COMPLETED',
            'CONFIRMED', 'DAYCARE', 'INPROGRESS', 'MEDBOARD', 'NOSHOW', 'PENDING',
            'PLANNED', 'LATE', 'RESERVATION', 'KEPT', 'RESCHEDULED', 'SCHEDULED',
            name='status'
        ),
        nullable=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'appointments',
        'status',
        existing_type=sa.Enum(
            'ADMITTED', 'CANCELLED', 'CHECKED_IN', 'CHECKING_OUT', 'COMPLETED',
            'CONFIRMED', 'DAYCARE', 'INPROGRESS', 'MEDBOARD', 'NOSHOW', 'PENDING',
            'PLANNED', 'LATE', 'RESERVATION', 'KEPT', 'RESCHEDULED',
            name='status'
        ),
        nullable=True
    )
    # ### end Alembic commands ###
