"""deleted Member.position

Revision ID: b4b6c5f2c256
Revises: 1a38b29d9a5f
Create Date: 2020-12-31 13:20:41.919775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4b6c5f2c256'
down_revision = '1a38b29d9a5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('members', 'position')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('position', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
