"""rename kpi value table and add external kpi value table

Revision ID: de76967e8612
Revises: 1e8a07b60f88
Create Date: 2020-09-01 15:56:02.366809

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

import ghostdb

# revision identifiers, used by Alembic.
revision = 'de76967e8612'
down_revision = '1e8a07b60f88'
branch_labels = None
depends_on = None


def upgrade():
    op.rename_table('kpi_value', 'kpi_value_internal')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kpi_value_external',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_source', postgresql.ENUM('PIMS', 'ERP', name='kpidatasource', create_type=False), nullable=True),
    sa.Column('kind', postgresql.ENUM('FINANCIAL_NET_REVENUE', 'FINANCIAL_NET_PROFIT', 'FINANCIAL_ACCOUNTS_RECEIVABLE', 'FINANCIAL_ACCOUNT_PAYABLE', 'FINANCIAL_COGS', 'FINANCIAL_EBITDA', 'FINANCIAL_CAPEX', 'FINANCIAL_OPEX', name='kpikind', create_type=False), nullable=True),
    sa.Column('value', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('corporation_id', ghostdb.db.sqltypes.UUID(), nullable=True),
    sa.Column('business_id', ghostdb.db.sqltypes.UUID(), nullable=True),
    sa.Column('provider_id', ghostdb.db.sqltypes.UUID(), nullable=True),
    sa.Column('client_id', ghostdb.db.sqltypes.UUID(), nullable=True),
    sa.Column('pet_id', ghostdb.db.sqltypes.UUID(), nullable=True),
    sa.Column('revenue_center_id', ghostdb.db.sqltypes.UUID(), nullable=True),
    sa.Column('department_id', ghostdb.db.sqltypes.UUID(), nullable=True),
    sa.Column('category_id', ghostdb.db.sqltypes.UUID(), nullable=True),
    sa.Column('class_id', ghostdb.db.sqltypes.UUID(), nullable=True),
    sa.Column('subclass_id', ghostdb.db.sqltypes.UUID(), nullable=True),
    sa.Column('servicetype_id', ghostdb.db.sqltypes.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], name=op.f('fk_kpi_value_external_business_id_businesses')),
    sa.ForeignKeyConstraint(['category_id'], ['glcode_category.id'], name=op.f('fk_kpi_value_external_category_id_glcode_category')),
    sa.ForeignKeyConstraint(['class_id'], ['glcode_class.id'], name=op.f('fk_kpi_value_external_class_id_glcode_class')),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_kpi_value_external_client_id_clients')),
    sa.ForeignKeyConstraint(['corporation_id'], ['corporations.id'], name=op.f('fk_kpi_value_external_corporation_id_corporations')),
    sa.ForeignKeyConstraint(['department_id'], ['glcode_department.id'], name=op.f('fk_kpi_value_external_department_id_glcode_department')),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], name=op.f('fk_kpi_value_external_pet_id_pets')),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], name=op.f('fk_kpi_value_external_provider_id_providers')),
    sa.ForeignKeyConstraint(['revenue_center_id'], ['glcode_revenuecenter.id'], name=op.f('fk_kpi_value_external_revenue_center_id_glcode_revenuecenter')),
    sa.ForeignKeyConstraint(['servicetype_id'], ['glcode_servicetype.id'], name=op.f('fk_kpi_value_external_servicetype_id_glcode_servicetype')),
    sa.ForeignKeyConstraint(['subclass_id'], ['glcode_subclass.id'], name=op.f('fk_kpi_value_external_subclass_id_glcode_subclass')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_kpi_value_external'))
    )
    # ### end Alembic commands ###


def downgrade():
    op.rename_table('kpi_value_internal', 'kpi_value')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kpi_value_external')
    # ### end Alembic commands ###
