name: GhostDB

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: vis_test
          POSTGRES_USER: vis
          POSTGRES_PASSWORD: vis
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: "PostgreSQL: configure extensions"
        run: |
          sudo apt install -y postgresql-client
          psql -h localhost -U vis -c "CREATE EXTENSION IF NOT EXISTS ltree;" vis_test
        env:
          PGPASSWORD: vis
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements/ci.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-
      - name: Config VIS PyPi Repository
        run: |
          mkdir -p ~/.config/pip/
          echo -e "[global]" >> ~/.config/pip/pip.conf
          echo -e "extra-index-url = ${{ secrets.VIS_PYPI_URL }}" >> ~/.config/pip/pip.conf
          echo -e "trusted-host = pypi.api.vet"
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/ci.txt
      - name: Tests
        env:
          PYTHONPATH: ..
          GHOSTDB_DB_DSN: postgresql://vis:vis@localhost:5432/vis_test
        run: |
          python -m pytest \
              --pylama \
              --ignore=./ghostdb/alembic \
              --junitxml=tests_results/junit.xml \
              --cov=. --cov-report=xml:tests_artifacts/coverage.xml --cov-report=html:tests_artifacts/coverage/ \
              ghostdb/
        if: ${{ job.status == 'success' }}
      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          path: tests_results/
        if: ${{ always() }}

  build-pkg:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Configure PyPi
        run: |
          echo -e "[distutils]" >> ~/.pypirc
          echo -e "index-servers = vis" >> ~/.pypirc
          echo -e "[vis]" >> ~/.pypirc
          echo -e "repository = $VIS_PYPI_URL" >> ~/.pypirc
          echo -e "username = ghostdb" >> ~/.pypirc
          echo -e "password = $GHOSTDB_PYPI_PASSWORD" >> ~/.pypirc
      - name: Build and Upload Package
        run: |
          python setup.py egg_info -b dev`date "+%Y%m%d%H%M"` sdist upload -r vis
        if: ${{ github.ref == 'refs/heads/master' }}
